<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src.txt</string>
	</array>
	<key>firstLineMatch</key>
	<string>(?x)^
		(=(t|h)=(.*?)=(t|h)=)
	</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Ceres</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^=(t)=(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.title.chapter</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.title.chapter</string>
			<key>end</key>
			<string>=t=$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^=h=(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.title.article</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.title.article</string>
			<key>end</key>
			<string>=h=$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>=([0-3]+)=(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.title.numbered</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.title.numbered</string>
			<key>end</key>
			<string>=([0-3]+)=</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^=b=(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.byline</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.byline</string>
			<key>end</key>
			<string>=b=$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>=d=(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.deck</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.deck</string>
			<key>end</key>
			<string>=d=</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\*\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.bold</string>
			<key>end</key>
			<string>\*\*</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\/</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.italic</string>
			<key>end</key>
			<string>\/\/</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\/\/\*\*)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.italicbold</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.italicbold</string>
			<key>end</key>
			<string>(\*\*\/\/)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\*\*\/\/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.italicbold</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.italicbold</string>
			<key>end</key>
			<string>(\/\/\*\*)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^-(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.list</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.list</string>
			<key>end</key>
			<string>$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>''</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.code.inline</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.code.inline</string>
			<key>end</key>
			<string>''</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;code php&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.php</string>
			<key>end</key>
			<string>(&lt;/code&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;code sql&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.code.block.sql</string>
			<key>end</key>
			<string>(&lt;/code&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;code xml&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.code.block.xml</string>
			<key>end</key>
			<string>(&lt;/code&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;code javascript&gt;)(.*?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.code.block.javascript</string>
			<key>end</key>
			<string>(&lt;/code&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;code python&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.code.block.python</string>
			<key>end</key>
			<string>(&lt;/code&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;code html&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.code</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.code.block.html</string>
			<key>end</key>
			<string>(&lt;/code&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\{figure )(.*?)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.figure</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.figure</string>
			<key>end</key>
			<string>(\}\})</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\{sidebar (.*?))</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.sidebar.title</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.sidebar</string>
			<key>end</key>
			<string>(\}\})</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ceres</string>
	<key>uuid</key>
	<string>874B621C-E80C-494A-A0E1-65EBDBE7D4B2</string>
</dict>
</plist>
